In [2]:
import numpy as np

# 1. Broadcasting

## a) Add a 1D array [1, 2, 3] to each row of a 2D array [[10, 20, 30], [40, 50, 60]].

In [3]:
arr1 = np.array([[10, 20, 30], [40, 50, 60]])
arr2 = np.array([1, 2, 3])
result1 = arr1 + arr2
print("1a) Broadcasting Add:\n", result1)

1a) Broadcasting Add:
 [[11 22 33]
 [41 52 63]]


## b) Multiply a 2D array [[1, 2], [3, 4]] by a 1D array [10, 20] column-wise.

In [5]:
arr3 = np.array([[1, 2], [3, 4]])
arr4 = np.array([[10], [20]])
result2 = arr3 * arr4
print("1b) Broadcasting Multiply:\n", result2)

1b) Broadcasting Multiply:
 [[10 20]
 [60 80]]


# 2. Indexing and Slicing (High Dimensional Arrays)

In [6]:
arr5 = np.arange(1, 25).reshape(2, 3, 4)

## a) Extract the second slice along axis 0.

In [7]:
result3 = arr5[1]
print("2a) Second Slice along Axis 0:\n", result3)

2a) Second Slice along Axis 0:
 [[13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]


## b) Extract all rows and the last column for all slices.

In [8]:
result4 = arr5[:, :, -1]
print("2b) All rows and the last column for all slices:\n", result4)

2b) All rows and the last column for all slices:
 [[ 4  8 12]
 [16 20 24]]


## c) Reverse the order of slices along axis 0.

In [9]:
result5 = arr5[::-1]
print("2c) Reverse the order of slices along Axis 0:\n", result5)

2c) Reverse the order of slices along Axis 0:
 [[[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]

 [[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]]


## d) Set all even elements in the array to -1.

In [10]:
arr5[arr5 % 2 == 0] = -1
print("2d) Set even elements to -1:\n", arr5)

2d) Set even elements to -1:
 [[[ 1 -1  3 -1]
  [ 5 -1  7 -1]
  [ 9 -1 11 -1]]

 [[13 -1 15 -1]
  [17 -1 19 -1]
  [21 -1 23 -1]]]


# 3. np.repeat

## a) Given arr = np.array([1, 2, 3, 4, 5, 6]), create a new array where every odd element is repeated twice.

In [11]:
arr6 = np.array([1, 2, 3, 4, 5, 6])
result6 = np.repeat(arr6[arr6 % 2 != 0], 2)
print("3a) Repeat odd elements twice:\n", result6)

3a) Repeat odd elements twice:
 [1 1 3 3 5 5]


## b) Given arr = np.array([1, 2, 3, 4, 5, 6]), create a new array where elements are repeated based on their value.

In [12]:
result7 = np.repeat(arr6, arr6)
print("3b) Repeat elements based on their value:\n", result7)

3b) Repeat elements based on their value:
 [1 2 2 3 3 3 4 4 4 4 5 5 5 5 5 6 6 6 6 6 6]


# 4. Normalizing


## a) Normalize a 1D array arr = np.array([10, 20, 30]) to have values between 0 and 1.

In [13]:
arr8 = np.array([10, 20, 30])
result8 = (arr8 - arr8.min()) / (arr8.max() - arr8.min())
print("4a) Normalized array:\n", result8)

4a) Normalized array:
 [0.  0.5 1. ]


# 5. Bonus Challenge

## a) Create a 3x3 matrix where each element at position (i, j) is i * j.

In [14]:
result9 = np.array([[i * j for j in range(3)] for i in range(3)])
print("5a) Matrix with i * j:\n", result9)

5a) Matrix with i * j:
 [[0 0 0]
 [0 1 2]
 [0 2 4]]


## b) Given a 4x4 matrix, replace all elements on the main diagonal with 0 without using a loop.

In [15]:
arr9 = np.ones((4, 4))
np.fill_diagonal(arr9, 0)
print("5b) 4x4 matrix with diagonal replaced by 0:\n", arr9)

5b) 4x4 matrix with diagonal replaced by 0:
 [[0. 1. 1. 1.]
 [1. 0. 1. 1.]
 [1. 1. 0. 1.]
 [1. 1. 1. 0.]]
